global:
  greptime:
    databaseName: public

greptimedb-standalone:
  enabled: false
  databaseName: public
  fullnameOverride: mdai-greptimedb
  extraVolumeMounts:
    - mountPath: /etc/greptimedb/auth
      name: auth
      readOnly: true
  extraVolumes:
    - name: auth
      secret:
        defaultMode: 420
        secretName: greptimedb-users-auth
  env:
    GREPTIMEDB_STANDALONE__USER_PROVIDER: "static_user_provider:file:/etc/greptimedb/auth/passwd"
  ## AWS start
  # objectStorage:
  #   s3:
  #     bucket: mdai-greptime-object-storage
  #     endpoint: s3.us-east-2.amazonaws.com
  #     region: us-east-2
  #     root: ""
  # persistence:
  #   storageClass: gp2
  #   size: 20Gi
  # serviceAccount:
  #   annotations:
  #     eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/mdai-greptime-irsa-role
  #   create: true
  #   name: greptimedb-standalone
## AWS end

greptimedb-cluster:
  enabled: false
  meta:
    backendStorage:
      etcd:
        endpoints:
          - mdai-etcd.mdai.svc.cluster.local:2379
    readinessProbe:
      initialDelaySeconds: 40
## AWS start
#  objectStorage:
#    s3:
#      bucket: mdai-greptime-object-storage
#      endpoint: s3.us-east-2.amazonaws.com
#      region: us-east-2
#      root: ""
#  datanode:
#    storage:
#      storageClassName: gp2
#      size: 20Gi
#    serviceAccount:
#      annotations:
#        eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/greptime-irsa-mdai-greptime-test
#      create: true
#      name: greptimedb-cluster
## AWS end

etcd:
  replicaCount: 3
  auth:
    rbac:
      create: false
    token:
      enabled: false
  global:
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: greptime/etcd
    tag: 3.6.1-debian-12-r3
## AWS start
#  persistence:
#    enabled: true
#    storageClass: gp2
#    accessModes:
#      - ReadWriteOnce
#    size: 8Gi
#    selector: {}
## AWS end

greptimedb-operator:
  enabled: false

kubeprometheusstack:
  prometheus:
    prometheusSpec:
      remoteWrite:
        - url: 'http://mdai-greptimedb.mdai.svc.cluster.local:4000/v1/prometheus/write?db={{ .Values.global.greptime.databaseName | default "public" }}'
          basicAuth:
            username:
              name: greptimedb-users-auth
              key: GREPTIME_USER
            password:
              name: greptimedb-users-auth
              key: GREPTIME_PASSWD
#          writeRelabelConfigs:
#            - sourceLabels: [__name__]
#              regex: '(essential_metric_1|essential_metric_2)'
#              action: keep
#            - sourceLabels: [ __meta_kubernetes_namespace ]
#              regex: 'mdai'
#              action: keep