thanos:
  enabled: false
  global:
    security:
      allowInsecureImages: true
  image:
    registry: quay.io/thanos
    repository: thanos
    tag: v0.41.0
  existingObjstoreSecret: kube-prometheus-stack-prometheus
  existingObjstoreSecretItems:
    - key: object-storage-configs.yaml
      path: objstore.yml

  query:
    dnsDiscovery:
      sidecarsService: "prometheus-operated"
      sidecarsNamespace: "mdai"

  compactor:
    enabled: true
    # aws
    serviceAccount:
      create: true
      name: "mdai-prometheus-thanos"
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::168005146325:role/mdai-thanos-irsa-role
    persistence:
      enabled: true
      storageClass: gp2

  storegateway:
    enabled: true
    # aws
    serviceAccount:
      create: true
      name: "mdai-prometheus-thanos"
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::168005146325:role/mdai-thanos-irsa-role
    persistence:
      enabled: true
      storageClass: gp2

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
