{{- $existing := lookup "v1" "Secret" .Release.Namespace "greptimedb-users-auth" -}}
{{- $greptimePassword := "" -}}
{{- if $existing -}}
  {{- $passwd := index $existing.data "passwd" | b64dec -}}
  {{- $greptimePassword = regexReplaceAll "^mdai=" $passwd "" -}}
{{- else -}}
  {{- $greptimePassword = randAlphaNum 32 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: greptimedb-users-auth
  labels:
    app: greptimedb
type: Opaque
data:
  passwd: {{ printf "mdai=%s" $greptimePassword | b64enc | quote }}
  GREPTIME_USER: {{ (index .Subcharts "greptimedb-standalone").Values.postgresUser | default "mdai" | b64enc | quote }}
  GREPTIME_PASSWD: {{ $greptimePassword | b64enc | quote }}
  GREPTIME_HOST: {{ printf "%s-greptimedb.%s.svc.cluster.local" .Release.Name .Release.Namespace | b64enc | quote }}
  GREPTIME_PORT: {{ (index .Subcharts "greptimedb-standalone").Values.postgresServicePort | toString | default "4003" | b64enc | quote }}
  GREPTIME_DATABASE: {{ (index .Subcharts "greptimedb-standalone").Values.databaseName | default "public" | b64enc | quote }}

