apiVersion: v1
kind: Secret
metadata:
  name: greptimedb-users-auth
  labels:
    app: greptimedb
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  passwd: {{ printf "mdai=%s" (randAlphaNum 32) | b64enc | quote }}
  GREPTIME_HOST: {{ printf "%s-greptimedb.%s.svc.cluster.local" .Release.Name .Release.Namespace | b64enc | quote }}
  GREPTIME_PORT: {{ (index .Subcharts "greptimedb-standalone").Values.postgresServicePort | default (int 4003) | quote }}
  GREPTIME_DATABASE: {{(index .Subcharts "greptimedb-standalone").Values.databaseName | default "mdai" | quote }}

