{{- if and .Values.nats.enabled .Values.nats.promExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mdai-hub.fullname" . }}-nats-metrics
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: {{ include "nats.instance" . }}
spec:
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: {{ include "nats.instance" . }}
    app.kubernetes.io/component: nats
  ports:
    - name: metrics
      port: 7777
      targetPort: 7777
{{- end }}
