---
{{- $cleanupSAName := printf "%s-pvc-cleanup-sa" (include "mdai-hub.fullname" .) }}
{{- $cleanupRoleName := printf "%s-pvc-cleanup-role" (include "mdai-hub.fullname" .) }}
{{- $cleanupBindingName := printf "%s-pvc-cleanup-binding" (include "mdai-hub.fullname" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $cleanupSAName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $cleanupRoleName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "-5"
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $cleanupBindingName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "-5"
subjects:
  - kind: ServiceAccount
    name: {{ $cleanupSAName }}
roleRef:
  kind: Role
  name: {{ $cleanupRoleName }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mdai-hub.fullname" . }}-pvc-cleanup
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      serviceAccountName: {{ $cleanupSAName }}
      restartPolicy: Never
      containers:
      - name: delete-pvc
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Deleting PVCs for release {{ .Release.Name }}..."
            kubectl delete pvc -l "app.kubernetes.io/instance={{ .Release.Name }}" --namespace {{ .Release.Namespace }}
      {{- with .Values.cleanup.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
