apiVersion: v1
kind: Secret
metadata:
  name: valkey-secret
  labels:
    app: valkey
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  VALKEY_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  VALKEY_ENDPOINT: {{ printf "%s.%s.svc.cluster.local:%d" (include "valkey.fullname" (dict "Values" .Values.valkey "Release" .Release "Chart" (dict "Name" "valkey"))) .Release.Namespace (int .Values.valkey.service.port) | b64enc | quote }}
